### ISSUE TITLE
ERE: Event Relation Extraction

### ISSUE THREAD

**Issue by EslamAli86** [THU-KEG/OmniEvent#48]
Hello,

Thank you for this amazing toolkit. I have a question as I tried to run the Code 2 example on page 4  in the paper (https://arxiv.org/pdf/2309.14258.pdf)

# event extraction & relation extraction
all_results = infer(text=text, task="EE & ERE")

That part of the code throws the following exception:

Traceback (most recent call last):
  File "/storage/home/grads/ehussein/OmniEvent/test.py", line 20, in <module>
    all_results = infer(text=text, task="ERE")
  File "/storage/home/grads/ehussein/OmniEvent/OmniEvent/infer.py", line 107, in infer
    assert task in ['ED', 'EAE', 'EE']
AssertionError

The toolkit does not support the ERE part yet. Do you think I need to do something to infer the event relation extraction? or will this part be released soon?

Thank you

**Comment by h-peng17** [comment]
Thanks for the reminder! we will release the ERE code and models in 2 weeks. And I'm attending EMNLP 2023 in Singapore. Welcome to our poster to communicate!

**Comment by EslamAli86** [comment]
Thank you so much for letting us know, we appreciate it. We are waiting for the new release. And good luck with your poster presentation @ EMNLP :)

**Comment by EslamAli86** [comment]
Hi Hao,

I hope this message finds you well. I was wondering if you have any plans to release the ERE module of OmniEvent. Its availability would greatly assist us in our research.

Thank you,

**Comment by h-peng17** [comment]
Hello, I'm very sorry for the delay in the release of OmniEvent-ERE due to recent busy schedules. If you urgently need the ERE module, I can send you the original OmniEvent-ERE code via email. Once this busy phase is over, I will integrate OmniEvent-ERE into the current repository.

**Comment by EslamAli86** [comment]
Hello Hao,

I appreciate you sharing your current repository for the ERE part. It seems that the model needs training on various datasets to predict different types of relationships between events. Unfortunately, I don't have access to most of these datasets. Could you please share either the trained models or the processed datasets?

Thank you for your assistance; I appreciate it.

**Comment by h-peng17** [comment]
You can get some processed datasets at this repository (https://github.com/THU-KEG/MAVEN-ERE). For all the ERE datasets that we use, we abide by their licenses and will open source them together with the codes.

**Comment by EslamAli86** [comment]
Hi Hao,

Thank you so much for providing most of the dataset, I understand you can
not provide the one that are distributed under licenses.

For the MAVEN-ERE dataset that is processed by the python script
maven-ere.py under OmniEvent-ERE/scripts/data_processing/MAVEN-ERE, there
seem to be a mismatch between the json format of the data under (
https://github.com/THU-KEG/MAVEN-ERE) and the expected json format read by
maven-ere.py. Could you please provide the MAVEN-ERE dataset in the json
format processed by the script  maven-ere.py?

Thank you and sorry for any inconvenience,

Eslam

**Comment by hoangthuytruc** [comment]
Hi @h-peng17 

I'm using your toolkit to train my own model on event extraction and plan to reuse it on event relation extraction. Could you send me the OmniEvent-ERE module via my email?

**Comment by h-peng17** [comment]
ok, I have sent it to you. Sorry for the delay, I will publish it soon.

**Comment by h-peng17** [comment]
@EslamAli86 Sorry for the late response. I remember there is only a format difference. Maybe you can convert it by yourself.

**Comment by Azzz123** [comment]
你好 我计划使用您的工具包做ERE任务 是否方便通过邮件发送相关模块？

**Comment by h-peng17** [comment]
@Azzz123 请提供你的邮箱，谢谢

**Comment by Azzz123** [comment]
@h-peng17 945577536@qq.com thks!

**Comment by faishiae** [comment]
Hi, 

Thank you for the amazing work! 
Recently I plan to use your toolkit to do some research, can you send me the ERE part? My email address is yuyanyangfeng1@gmail.com. Many thanks!

**Comment by Azzz123** [comment]
> @Azzz123 请提供你的邮箱，谢谢

hello，[945577536@qq.com](mailto:945577536@qq.com)this is my email address，hope to receive the ERE part. thks a lot！
