### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by Azzz123** [THU-KEG/OmniEvent#63]
../aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [202,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "/opt/data/private/lxt/OmniEvent/examples/ED/sequence_labeling.py", line 100, in <module>
    trainer.train()
  File "/opt/data/private/lxt/miniconda3/envs/bert/lib/python3.9/site-packages/transformers/trainer.py", line 1498, in train
    return inner_training_loop(
  File "/opt/data/private/lxt/miniconda3/envs/bert/lib/python3.9/site-packages/transformers/trainer.py", line 1740, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/opt/data/private/lxt/miniconda3/envs/bert/lib/python3.9/site-packages/transformers/trainer.py", line 2470, in training_step
    loss = self.compute_loss(model, inputs)
  File "/opt/data/private/lxt/miniconda3/envs/bert/lib/python3.9/site-packages/transformers/trainer.py", line 2502, in compute_loss
    outputs = model(**inputs)
  File "/opt/data/private/lxt/miniconda3/envs/bert/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/data/private/lxt/miniconda3/envs/bert/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/data/private/lxt/OmniEvent/examples/ED/../../OmniEvent/model/model.py", line 196, in forward
    outputs = self.backbone(input_ids=input_ids,
  File "/opt/data/private/lxt/miniconda3/envs/bert/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/data/private/lxt/miniconda3/envs/bert/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/data/private/lxt/miniconda3/envs/bert/lib/python3.9/site-packages/transformers/models/roberta/modeling_roberta.py", line 841, in forward
    embedding_output = self.embeddings(
  File "/opt/data/private/lxt/miniconda3/envs/bert/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/data/private/lxt/miniconda3/envs/bert/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/data/private/lxt/miniconda3/envs/bert/lib/python3.9/site-packages/transformers/models/roberta/modeling_roberta.py", line 133, in forward
    position_embeddings = self.position_embeddings(position_ids)
  File "/opt/data/private/lxt/miniconda3/envs/bert/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/data/private/lxt/miniconda3/envs/bert/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/data/private/lxt/miniconda3/envs/bert/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 190, in forward
    return F.embedding(
  File "/opt/data/private/lxt/miniconda3/envs/bert/lib/python3.9/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

  0%|                                                                                                                                                                                 | 0/930 [00:01<?, ?it/s]

how to solve？

**Comment by h-peng17** [comment]
I don't know the specific details of the errors. Maybe there are some dependencies version conflicts in your env.
